name: frontend ci cd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: get code
      - uses: actions/checkout@v2
        run: |
          npm install
          npm run build
        
